### PR TITLE
Fixes wrong keyIdentifiers of modifiers in the Linux and Windows Chromium versions

### LINKED ISSUE #65: Shift keyevent interrupts matching a key sequence
Investigating a [vim-mode bug](https://github.com/atom/vim-mode/issues/403) about bindings like 'i (' and 'i {' being ignored, I found the following: pressing shift alone generates a keydown event. Thus, when typing a sequence like 'i (', the 'i' gives a partial match. Then, on my keyboard, typing '(' involves pressing shift and 9 simultaneously. The shift key alone, however, generates a separate keydown event before the 9 keypress, so the partial matching gets interrupted before the actual '(' keydown event comes in. I verified this by console.logging the keydown events received on Chromium 39, Linux.

EDIT: this can be also verified by having vim-mode on, looking at the keybinding resolver. In command mode, press first 'c', then 'i'. There's the list of partial matches. As soon as I push down the shift key to type '(', the list of partial matches disappears before I could type in the actual '('.

EDIT 2: This might be Linux specific.

### PR DESCRIPTION
**Pull request by wvanlint**
I added translations for wrong keyIdentifiers of modifiers in the Linux and Windows Chromium versions.
I verified the keyIdentifiers in Chrome on Linux using:
```javascript
document.addEventListener('keydown', function (e) { console.log(e) });
```
This fixes #65.

I also refactored the preprocessing done in keystrokeForKeyboardEvent so it should be easier to handle bugs like this now.

### CODE REVIEW

**Comment by wvanlint** [comment]
@nathansobo Any comments? Thanks in advance for taking a look!

File: src/helpers.coffee [hunk 1]
```diff
@@ -103,46 +112,26 @@ exports.normalizeKeystrokes = (keystrokes) ->
...
-
-      if event.location is KeyboardEvent.DOM_KEY_LOCATION_NUMPAD
-        # This is a numpad number
-        charCode = numpadToASCII(charCode)
-
-      charCode = event.which if not isASCII(charCode) and isASCII(event.keyCode)
-      key = keyFromCharCode(charCode)
-    else
-      key = event.keyIdentifier.toLowerCase()
+  prep_event = new PreprocessableKeyboardEvent event
```
Comment (nathansobo) [inline src/helpers.coffee]: I'd prefer to call a method that returns an object rather than building an object that we then mutate. Also, variables in our codebase are `camelCased`.

**Comment by nathansobo** [comment]
Thanks for digging in on this. These kind of changes scare me because it's hard to predict what will break from the diff. Having the minimum possible diff to apply the fix would help a lot, then we can discuss a broader reorganization in another PR.

If you can get me a more minimal diff, then maybe I can talk @izuzak into helping me make sure it doesn't break anything on various platforms.

**Comment by wvanlint** [comment]
Thanks! I cut down the change to be as minimal as possible.

I verified that the original and new tests are passing with `apm test`.
Atom works as expected on Linux when rebuilt and the bug looks fixed.

The change only does a translation for certain keyIdentifiers on Linux and Windows, and those keyIdentifiers are normally not generated if Chromium followed the DOM specification, so hopefully not too much cross-platform testing is needed.
http://www.w3.org/TR/2007/WD-DOM-Level-3-Events-20071221/keyset.html#KeySet-Set

**Comment by nathansobo** [comment]
Thanks for reducing the diff. You're right that this looks fairly conservative in only dealing with specific keys on specific platforms.

**Comment by nathansobo** [comment]
Thanks a lot. This will be out with `v0.180.0`.
